### ISSUE TITLE
开发环境下  刷新页面为什么hash会丢失

### ISSUE THREAD

**Issue by dingshaohua-cn** [vuepress/vuepress-next#1014] opened 2022-08-05 02:29 UTC
### Description

![2](https://user-images.githubusercontent.com/18003391/182988832-d0023e99-ae3f-43e7-b13a-92015f68a8d7.gif)

### Reproduction

null

### Used Package Manager

yarn

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 9.20 GB / 15.68 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.36.1.
  Browsers:
    @vuepress/plugin-palette:  2.0.0-beta.49
    @vuepress/plugin-prismjs:  2.0.0-beta.49
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49
    @vuepress/theme-default:  2.0.0-beta.49
    @vuepress/utils:  2.0.0-beta.49
    vue:  3.2.37
    vue-loader: Not Found
    vue-router:  4.1.3
    vuepress: ^2.0.0-beta.49 => 2.0.0-beta.49
    vuepress-vite:  2.0.0-beta.49
```

**Comment by meteorlxy** [comment] 2022-08-08 09:01
Duplicate of #991

**Closed by meteorlxy** 2022-08-08 09:01 UTC
