### ISSUE TITLE
[Bug report] Some vue errors since update to 2.0.0-beta.45

### ISSUE THREAD

**Issue by LouisMazel** [vuepress/vuepress-next#899] opened 2022-05-18 18:10 UTC
### Description

Hi,

Since I updated vuepress from 2.0.0-beta.33 to 2.0.0-beta.45, I have some errors in production.

All is fine in local, but when I release the documentation on Github Pages, I some bugs with external components installed in `client.ts`

I have some errors like: 
- `TypeError: Cannot read properties of null (reading 'setupContext')`
- `TypeError: Cannot read properties of null (reading 'nextSibling')`
- `TypeError: Cannot read properties of null (reading 'refs')`
- `TypeError: Cannot read properties of null (reading 'isCE')`

These components come from my own components library, installed locally (not from npm). I have a monorepo.
In my package.json: `"maz-ui": "file:../lib"`

Repo links: 
- Install external components with enhance function - [clients.ts](https://github.com/LouisMazel/maz-ui/blob/master/packages/docs/docs/.vuepress/client.ts)
- My config - [config.ts](https://github.com/LouisMazel/maz-ui/blob/master/packages/docs/docs/.vuepress/config.ts)

Do you think it's a SSR error ? 

### Reproduction

https://louismazel.github.io/maz-ui-3/components/maz-btn.html

### Used Package Manager

npm

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 308.00 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /opt/homebrew/Cellar/node@16/16.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/Cellar/node@16/16.13.0/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: 97.0
    Safari: 15.4
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.45
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.45
    @vuepress/client:  2.0.0-beta.45
    @vuepress/core:  2.0.0-beta.45
    @vuepress/markdown:  2.0.0-beta.45
    @vuepress/plugin-active-header-links:  2.0.0-beta.45
    @vuepress/plugin-back-to-top:  2.0.0-beta.45
    @vuepress/plugin-container:  2.0.0-beta.45
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.45
    @vuepress/plugin-git:  2.0.0-beta.45
    @vuepress/plugin-google-analytics: ^2.0.0-beta.43 => 2.0.0-beta.45
    @vuepress/plugin-medium-zoom: ^2.0.0-beta.43 => 2.0.0-beta.45
    @vuepress/plugin-nprogress:  2.0.0-beta.45
    @vuepress/plugin-palette:  2.0.0-beta.45
    @vuepress/plugin-prismjs:  2.0.0-beta.45
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: ^2.0.0-beta.43 => 2.0.0-beta.45
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.45
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.45
    @vuepress/theme-default:  2.0.0-beta.45
    @vuepress/utils:  2.0.0-beta.45
    vue: ^3.2.33 => 3.2.33
    vue-loader: Not Found
    vue-router:  4.0.15
    vuepress: ^2.0.0-beta.43 => 2.0.0-beta.45
    vuepress-vite:  2.0.0-beta.45
    vuepress-webpack: Not Found
```

**Comment by LouisMazel** [comment] 2022-05-18 21:26
I tried to use it, bu no results : 

```ts
export default defineUserConfig({
  ...
  bundler: viteBundler({
    viteOptions: {
      optimizeDeps: {
        include: ['maz-ui']
      },
    },
  }),
  ...
})
```

**Comment by meteorlxy** [comment] 2022-05-19 02:53
You can try to build with `--debug` flag to check if there are any helpful debug messages in the browser. I'll also try to figure it out.

> I tried to use it, but no results :

`optimizeDeps` is for dev only, not for build.

**Comment by meteorlxy** [comment] 2022-05-19 03:01
Also, a minimal reproduction would be more helpful

**Comment by meteorlxy** [comment] 2022-05-19 03:57
Well, your repo is complicated to reproduce. According to the error message, I think this could be duplicate of #688 and #897. You can reopen it with another minimal reproduction if you think it not a duplicate.

**Closed by meteorlxy** 2022-05-19 03:57 UTC

**Comment by LouisMazel** [comment] 2022-05-24 10:00
@meteorlxy 
I found why I have this error. 
It's because I use local components from a recursive folder of my monorepo as npm depedency : `"maz-ui": "file:../lib"`

If I move the `lib` directory in the root folder of the vuepress project and use the local depedency like that: `"maz-ui": "file:lib"` --> I don't have any bugs.

It's a new behavior from the new version.

Thanks for your advices !
