### ISSUE TITLE
[Bug report] Incorrect "internal" links when using `base` config

### ISSUE THREAD

**Issue by NoahTheDuke** [vuepress/vuepress-next#58] opened 2021-02-09 20:49 UTC
### Description

It seems that the `base` config setting isn't being propagated to "internal" links, leading to incorrect links.

In my config, I have set the base config: `base: "/fixture-riveter/"`. Then in the docs folder, in `/api/README.md`, I have written `[fr](/api/fr/)` to link to `/api/fr/README.md`. The generated incorrect link (with svg elided for readability) is:

```html
<a href="/api/fr/" target="_blank" rel="noopener noreferrer">fr api<span><svg ...></svg><span class="sr-only">open in new window</span></span></a>
```

When working locally, if I remove the `base` setting, the link is now the correct `<a href="/api/fr/" class="">fr api</a>`. But this doesn't work when I push to my github pages, obviously.

### Steps to reproduce

The incorrect link can be seen [here](https://batterii.github.io/fixture-riveter/api/).

- Reproduction link / repo: https://github.com/Batterii/fixture-riveter/blob/master/docs/api/README.md

### Expected behavior

Links are generated correctly.

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
$ npx vuepress info

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 2.02 GB / 32.00 GB
    Shell: 5.0.17 - /usr/local/bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nodenv/versions/12.13.0/bin/node
    Yarn: Not Found
    npm: 7.5.3 - ~/.nodenv/versions/12.13.0/bin/npm
  Utilities:
    Git: 2.29.1 - /usr/local/bin/git
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Not Found
    Firefox: 85.0.1
    Safari: 13.1
  npmPackages:
    @vuepress/bundler-webpack:  2.0.0-alpha.20
    @vuepress/cli:  undefined (2.0.0-alpha.20)
    @vuepress/client:  2.0.0-alpha.20
    @vuepress/core:  2.0.0-alpha.20
    @vuepress/markdown:  2.0.0-alpha.20
    @vuepress/plugin-active-header-links:  2.0.0-alpha.20
    @vuepress/plugin-back-to-top:  2.0.0-alpha.20
    @vuepress/plugin-container:  2.0.0-alpha.20
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-alpha.21
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-alpha.20
    @vuepress/plugin-nprogress:  2.0.0-alpha.20
    @vuepress/plugin-palette-stylus:  2.0.0-alpha.20
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/shared:  2.0.0-alpha.20
    @vuepress/theme-default:  2.0.0-alpha.21
    @vuepress/theme-vue: Not Found
    @vuepress/utils:  2.0.0-alpha.20
    vue:  3.0.5
    vue-loader:  16.1.2
    vue-router:  4.0.3
    vuepress: ^2.0.0-alpha.21 => 2.0.0-alpha.21
```

**Comment by meteorlxy** [comment] 2021-02-10 02:15
That's the expected behavior.

Consider if both of the following links a available:

- `/api/fr/`
- `/fixture-riveter/api/fr/`

The first one is out of your VuePress site, but it's under the same hostname.

In your case, you are using **absolute path**, so VuePress will treat it as an external link and keep the link as is.

**Comment by meteorlxy** [comment] 2021-02-10 02:17
So it's better to use **relative path**:

- Don't need to consider the `base`.
- It's also a valid link when users are browsing the markdown files on GitHub.

**Comment by NoahTheDuke** [comment] 2021-02-10 03:25
Ah, okay. Thanks for the quick reply!

Maybe it would be helpful to note this in the docs for `base`? The examples make it seem more "magical".

**Comment by meteorlxy** [comment] 2021-02-10 06:46
Yeah, that's why I tagged this issue `documentation` and didn't close it.

**Comment by NoahTheDuke** [comment] 2021-02-10 15:13
I hate to keep bothering you about this, but I'm still having trouble getting any links in markdown to work right with `base`. (Is there a slack channel or somewhere I can ask for help without spamming this issue?)

Source code for the below is [here](https://github.com/Batterii/fixture-riveter/blob/master/docs/api/README.md) and the rendered page is [here](https://batterii.github.io/fixture-riveter/api).

Given:

```js
const config = {
    // ...
    base: "/fixture-riveter/",
    // ...
}
```

```md
### Relative links

[in parent directory](../README.md)

[in same directory](./adapter.md)

[in child directory](./exports/README.md)

[in adjacent directory](../guide/README.md)

### Absolute links

[in parent directory](/fixture-riveter/api/README.md)

[in same directory](/fixture-riveter/api/adapter.md)

[in child directory](/fixture-riveter/api/exports/README.md)

[in adjacent directory](/fixture-riveter/api/guide/README.md)
```

The output html is:
```html
<h3 id="relative-links"><a class="header-anchor" href="#relative-links">#</a> Relative links</h3>
<p><a href="/fixture-riveter/fixture-riveter/" class="">in parent directory</a></p>
<p><a href="/fixture-riveter/fixture-riveter/api/adapter.html" class="">in same directory</a></p>
<p><a href="/fixture-riveter/fixture-riveter/api/exports/" class="">in child directory</a></p>
<p><a href="/fixture-riveter/fixture-riveter/guide/" class="">in adjacent directory</a></p>

<h3 id="absolute-links"><a class="header-anchor" href="#absolute-links">#</a> Absolute links</h3>
<p><a href="/fixture-riveter/fixture-riveter/api/" class="">in parent directory</a></p>
<p><a href="/fixture-riveter/fixture-riveter/api/adapter.html" class="">in same directory</a></p>
<p><a href="/fixture-riveter/fixture-riveter/api/exports/" class="">in child directory</a></p>
<p><a href="/fixture-riveter/fixture-riveter/api/guide/" class="">in adjacent directory</a></p>
```

**Comment by meteorlxy** [comment] 2021-02-10 16:15
No worry, we are still in alpha stage and likely to have some issues. Let me take a check for that

**Comment by meteorlxy** [comment] 2021-02-10 16:19
Got the reason.

**Closed** 2021-02-10 17:02 UTC
Labels: bug, documentation

**Comment by meteorlxy** [comment] 2021-02-10 17:14
v2.0.0-alpha.23 fixes this. Let me know if you still have problems.

---

Our documentation does not use `base`, so it has not been fully tested.

Do not hesitate to report if you meet any problems.

Thanks a lot!
