### ISSUE TITLE
[Bug report] Code is not aligned with line numbers

### ISSUE THREAD

**Issue by nibazshab** [vuepress/vuepress-next#1040] opened 2022-08-23 10:57 UTC
### Description

at __code block__ , it is easy to find the Code is not aligned with line numbers

this picture is from your offical site, and i find many vuepress2's site, all have this bug, include of me

![](https://fars.ee/T6CV.jpg)

and this is from [my site](https://nibazshab.github.io/app/aria2.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

![](https://fars.ee/zi-D.jpg)

### Reproduction

https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation

https://nibazshab.github.io/app/aria2.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

### Used Package Manager

yarn

### System Info

```shell
$ vuepress info

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
    Memory: 918.90 MB / 3.59 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.9.0 - /tmp/yarn--1661252137425-0.1813988074204187/node
    Yarn: 1.22.19 - /tmp/yarn--1661252137425-0.1813988074204187/yarn
    npm: Not Found
  Utilities:
    Git: 2.30.2 - /usr/bin/git
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.49
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49
    @vuepress/client:  2.0.0-beta.49
    @vuepress/core:  2.0.0-beta.49
    @vuepress/markdown:  2.0.0-beta.49
    @vuepress/plugin-active-header-links:  2.0.0-beta.49
    @vuepress/plugin-back-to-top:  2.0.0-beta.49
    @vuepress/plugin-container:  2.0.0-beta.49
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49
    @vuepress/plugin-git:  2.0.0-beta.49
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49
    @vuepress/plugin-nprogress:  2.0.0-beta.49
    @vuepress/plugin-palette:  2.0.0-beta.49
    @vuepress/plugin-prismjs:  2.0.0-beta.49
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-theme-data:  2.0.0-beta.49
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49
    @vuepress/theme-default:  2.0.0-beta.49
    @vuepress/utils:  2.0.0-beta.49
    vue:  3.2.37
    vue-loader: Not Found
    vue-router:  4.1.4
    vuepress: ^2.0.0-beta.49 => 2.0.0-beta.49
    vuepress-vite:  2.0.0-beta.49
    vuepress-webpack: Not Found
```

**Comment by meteorlxy** [comment] 2022-08-25 13:55
Duplicate of #901

**Closed by meteorlxy** 2022-08-25 13:55 UTC
