### ISSUE TITLE
[Feature request] Is it possible to modify the content of config.ts without restarting the project?

### ISSUE THREAD

**Issue by social-uni** [vuepress/vuepress-next#637] opened 2022-01-17 15:59 UTC
Is it possible to modify the content of config.ts without restarting the project?

I need to restart the project every time I modify the route，it's too much trouble，very bad

Is it possible to modify the router without restarting the project, just like vue, it can take effect

**Comment by meteorlxy** [comment] 2022-01-22 18:20
If you are using Windows, it should be duplicate of #611

**Closed by meteorlxy** 2022-01-22 18:20 UTC
