### ISSUE TITLE
[Bug report] Error when switching packaging tools

### ISSUE THREAD

**Issue by qsyyke** [vuepress/vuepress-next#632] opened 2022-01-16 07:24 UTC
### Description
I built it according to the official website and installed this dependency of vuepress@next,the operation is normal, but when I follow the prompt, execute the command `npm install -D vuepress-webpack@next`, want to switch the packaging tool to webpack,running the `npm run docs:build` command will report the following error
```
info Initializing VuePress and preparing data...
✖ Compiling with webpack - failed
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.        
 - configuration[0].plugins[3] misses the property 'apply'. Should be:
   function
   -> The run point of the plugin, required method.
    at validate (D:\theme-aurora\use\default\node_modules\schema-utils\dist\validate.js:105:11)
    at validateSchema (D:\theme-aurora\use\default\node_modules\webpack\lib\validateSchema.js:78:2)
    at create (D:\theme-aurora\use\default\node_modules\webpack\lib\webpack.js:111:24)
    at webpack (D:\theme-aurora\use\default\node_modules\webpack\lib\webpack.js:142:47)
    at f (D:\theme-aurora\use\default\node_modules\webpack\lib\index.js:58:16)
    at D:\theme-aurora\use\default\node_modules\@vuepress\bundler-webpack\lib\build\createBuild.js:28:13
    at new Promise (<anonymous>)
    at D:\theme-aurora\use\default\node_modules\@vuepress\bundler-webpack\lib\build\createBuild.js:27:15
    at async D:\theme-aurora\use\default\node_modules\@vuepress\utils\lib\withSpinner.js:12:24
    at async Object.build (D:\theme-aurora\use\default\node_modules\@vuepress\bundler-webpack\lib\build\createBuild.js:13:5)
```

### Steps to reproduce

- Reproduction link / repo: [vuepress-test](https://github.com/qsyyke/vuepress-test)

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
$ vuepress info
- Collecting Environment Info

  System:
    OS: Windows 10 10.0.22523
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 2.70 GB / 15.77 GB
  Binaries:
    Node: 16.13.1 - D:\Environment\node\node.EXE
    Yarn: 1.22.17 - D:\Environment\node\node_global\yarn.CMD
    npm: 8.1.2 - D:\Environment\node\npm.CMD
  Utilities:
    Git: 2.31.1. - /mingw64/bin/git
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22523.1000.0), Chromium (97.0.1072.55)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.33
    @vuepress/bundler-webpack:  2.0.0-beta.33
    @vuepress/cli: ^2.0.0-beta.33 => 2.0.0-beta.33
    @vuepress/client:  2.0.0-beta.33
    @vuepress/core:  2.0.0-beta.33
    @vuepress/markdown:  2.0.0-beta.33
    @vuepress/plugin-active-header-links:  2.0.0-beta.33
    @vuepress/plugin-back-to-top:  2.0.0-beta.33
    @vuepress/plugin-container:  2.0.0-beta.33
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.33
    @vuepress/plugin-git:  2.0.0-beta.33
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.33
    @vuepress/plugin-nprogress:  2.0.0-beta.33
    @vuepress/plugin-palette:  2.0.0-beta.33
    @vuepress/plugin-prismjs:  2.0.0-beta.33
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.33
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.33
    @vuepress/theme-default:  2.0.0-beta.33
    @vuepress/utils:  2.0.0-beta.33
    vue:  3.2.26
    vue-loader:  17.0.0
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.33 => 2.0.0-beta.33
    vuepress-vite:  2.0.0-beta.33
    vuepress-webpack: ^2.0.0-beta.33 => 2.0.0-beta.33
```

**Comment by meteorlxy** [comment] 2022-01-21 19:13
Seems that this is duplicate of #635, which was caused by a bug of mini-css-extract-plugin.

**Closed by meteorlxy** 2022-01-21 19:13 UTC

**Comment by qsyyke** [comment] 2022-01-22 11:53
> Seems that this is duplicate of #635, which was caused by a bug of mini-css-extract-plugin.

Yes, need to use a lower version for mini-css-extract-plugin
