### ISSUE TITLE
[Bug report] Some files are incorrectly passed to node esm loader

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1060] opened 2022-08-29 10:53 UTC
### Description

See some issues report like:

- https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2171
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2172

Here is the output code:

```ts
// vuepress-shared/client/index.ts
/* some code */;import"./styles/message.scss";// xxxxx more code
```

I am expecting the bundler should handle scss file with sass (vite) or sass-loader (webpack) correctly, instead of passing the file to node esm loader:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".scss" for node_modules/.pnpm/vuepress-shared@2.0.0-beta.94/node_modules/vuepress-shared/lib/client/styles/message.scss
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:165:28)
    at ESMLoader.load (node:internal/modules/esm/loader:608:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:464:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:483:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:441:34)
 ELIFECYCLE  Command failed with exit code 1.
```

No code changes from none ESM version to currect version. The output code is always esm, and always being imported on client side.

I think this is something related to bunder. As this is happening only during build stage (dev server is working fine)

### Reproduction

https://github.com/MoonLord-LM/MyPages Comming from a issue

### Used Package Manager

npm

### System Info

```shell
not related I guess, starting from beta.50
```

**Comment by MoonLord-LM** [comment] 2022-08-29 16:31
mark

**Comment by Mister-Hope** [comment] 2022-08-30 05:43
Also, here are some new issues:

- https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2182
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2181

**Comment by meteorlxy** [comment] 2022-08-30 11:20
Could not reproduce it, as there is no lockfile in the repo your provided.

**Comment by MoonLord-LM** [comment] 2022-08-31 03:24
> 

https://github.com/MoonLord-LM/MyPages/runs/8105848221?check_suite_focus=true

**Comment by MoonLord-LM** [comment] 2022-09-01 19:28
It seems fixed now.

    "vuepress-plugin-md-enhance": "^2.0.0-beta.97"

**Closed** 2022-09-02 02:31 UTC
Labels: need reproduction

**Comment by its2easy** [comment] 2022-09-16 13:12
I get an error when I'm trying to import my theme from node_modules
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for D:\my_project_path\node_modules\@its2easy\vuepress2-theme\theme\index.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:82:21)
```
Could it be related to this issue? 
Seems like it started from beta.50. I know it's better to compile ts but it worked before and it's working now if I copy the theme folder from node_modules to project folder.

**Comment by meteorlxy** [comment] 2022-09-16 13:37
> I'm trying to import my theme from node_modules

Do not publish your package in `.ts`. Compile it to `.js` first.

**Comment by its2easy** [comment] 2022-09-16 15:11
@Mister-Hope but why in the second case the imported file is not processed by tsc like with local theme import?
```
import vuepressTheme from './theme/index.ts'; // works
import vuepressTheme from 'package/index.ts'; // doesn't work
```

**Comment by Mister-Hope** [comment] 2022-09-16 17:00
The first one is considered as source file and proceeded by bundler(client) or esbuild(node), while the second one is considered as production code.

**Comment by its2easy** [comment] 2022-09-16 19:32
ok, thanks

**Comment by TaTo30** [comment] 2023-05-19 21:34
I'm getting a similar error with depedency's css file.

Any ideas?

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\project_path\docs\node_modules\pdfjs-dist\web\pdf_viewer.css
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
```
