### ISSUE TITLE
[Feature request]  compiling and rendering with multi workers

### ISSUE THREAD

**Issue by lslzl3000** [vuepress/vuepress-next#995] opened 2022-07-23 08:44 UTC
### Clear and concise description of the problem

Try to build with 1000 .md files
It takes more than 9min to compile and render~~ too too slow

Macbook Pro M.2 2022, the cpu performance is good enough
Should be much faster

### Suggested solution

Looks like the build process is working in 1 thread 
can we enable multi-workers?
e.g Start [build.ts ](https://github.com/vuepress/vuepress-next/blob/main/packages/%40vuepress/bundler-vite/src/build/build.ts) in N workers, each build 1/N numbers of pages

**Comment by lslzl3000** [comment] 2022-07-23 09:04
Also the build process would cause memory leak
Have to work with `--max_old_space_size=8192`

Is there any better way to manage node memory?
e.g.  release objects after compiling/rendering each page

**Comment by lslzl3000** [comment] 2022-07-23 10:51
Tested with VitePress, same 1000 .md files
### **!! VitePress only takes 15.9s !!** to build and render all files

**Comment by meteorlxy** [comment] 2022-07-26 06:25
Duplicate of #994

**Closed by meteorlxy** 2022-07-26 06:25 UTC
