### ISSUE TITLE
[Bug report] Invalid value used as weak map key

### ISSUE THREAD

**Issue by gtn1024** [vuepress/vuepress-next#222] opened 2021-06-18 16:19 UTC
### Description

When I use `<center></center>` in `docs/README.md`, it gets wrong.

### Steps to reproduce

- Reproduction link / repo: [https://github.com/gtn1024/vuepress-next-bug](https://github.com/gtn1024/vuepress-next-bug)

### Screenshots

![image](https://user-images.githubusercontent.com/69113276/122591640-cc3a2800-d095-11eb-8223-46ede446ba8a.png)

### Environment info

- Browser: Chrome
- Output of `vuepress info`: 

```bash
➜  vuepress-next-bug git:(main) ✗ npx vuepress info

  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 107.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Utilities:
    Git: 2.30.1 - /usr/bin/git
  Browsers:
    Chrome: 91.0.4472.106
    Edge: 91.0.864.53
    Firefox: 89.0.1
    Safari: 14.1.1
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.18 
    @vuepress/cli:  2.0.0-beta.18 
    @vuepress/client:  2.0.0-beta.18 
    @vuepress/core:  2.0.0-beta.18 
    @vuepress/markdown:  2.0.0-beta.18 
    @vuepress/plugin-active-header-links:  2.0.0-beta.18 
    @vuepress/plugin-back-to-top:  2.0.0-beta.18 
    @vuepress/plugin-container:  2.0.0-beta.18 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.18 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.18 
    @vuepress/plugin-nprogress:  2.0.0-beta.18 
    @vuepress/plugin-palette:  2.0.0-beta.18 
    @vuepress/plugin-prismjs:  2.0.0-beta.18 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.18 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.18 
    @vuepress/theme-default:  2.0.0-beta.18 
    @vuepress/theme-vue: Not Found
    @vuepress/utils:  2.0.0-beta.18 
    vue:  3.1.1 
    vue-loader:  16.2.0 
    vue-router:  4.0.9 
    vuepress: ^2.0.0-beta.18 => 2.0.0-beta.18 
    vuepress-vite: Not Found
```

**Comment by meteorlxy** [comment] 2021-06-18 16:39
Duplicate of #201.

In short, avoid using deprecated html tags, or set [compilerOptions.isCustomElement](https://v3.vuejs.org/api/application-config.html#compileroptions-iscustomelement)

**Comment by nsznsznjsz** [comment] 2021-06-18 16:39
I think it's duplicated of #186, #201 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

**Closed by meteorlxy** 2021-06-18 16:39 UTC

**Comment by gtn1024** [comment] 2021-06-18 16:49
@meteorlxy I think it should be written to the VuePress Document to highlight this feature as many people may ignore it.

**Comment by meteorlxy** [comment] 2021-06-18 16:50
Sure. We'll update the docs later
