### ISSUE TITLE
[Bug report] The dark theme experience is not good

### ISSUE THREAD

**Issue by whp98** [vuepress/vuepress-next#558] opened 2021-12-10 09:57 UTC
### Description

When using a black theme, there will be white flickering, and then the interface will become black. The experience is not good

### Steps to reproduce

press f5 
- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by meteorlxy** [comment] 2021-12-13 11:54
Duplicate of #387. You can also find a workaround there

**Closed by meteorlxy** 2021-12-13 11:54 UTC
