### ISSUE TITLE
[Bug report] Fails to update site after config file is added or updated

### ISSUE THREAD

**Issue by CxRes** [vuepress/vuepress-next#598] opened 2021-12-29 14:14 UTC
### Description

Pages are not updated to reflect addition of or changes in `.vuepress/config.js`.

I am looking at the page title and description in the Hero Page elements

### Steps to reproduce

1. Run the dev server on a virgin repo.
2. Add a config.js file.

Nothing happens

3. Close the dev server and restart it.

Configuration updates

4.  Change a field like title in 'config.js'.

Dev server restarts (or at least message to that effect), but page does not update. I have refreshed the browser and opened the page in a different browser. The page is not updated irrespective.

5. Cut the server and restart.

Text is updated.

### Expected behavior

The addition and/or update of config file should cause an update to the pages.

### Environment info

- Browser: Brave, Firefox
- Output of `vuepress info`:
```bash
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
    Memory: 1.30 GB / 7.91 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.30.1. - /mingw64/bin/git
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.32
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.32
    @vuepress/client:  2.0.0-beta.32
    @vuepress/core:  2.0.0-beta.32
    @vuepress/markdown:  2.0.0-beta.32
    @vuepress/plugin-active-header-links:  2.0.0-beta.32
    @vuepress/plugin-back-to-top:  2.0.0-beta.32
    @vuepress/plugin-container:  2.0.0-beta.32
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.32
    @vuepress/plugin-git:  2.0.0-beta.32
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.32
    @vuepress/plugin-nprogress:  2.0.0-beta.32
    @vuepress/plugin-palette:  2.0.0-beta.32
    @vuepress/plugin-prismjs:  2.0.0-beta.32
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.32
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.32
    @vuepress/theme-default:  2.0.0-beta.32
    @vuepress/utils:  2.0.0-beta.32
    vue:  3.2.26
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.32 => 2.0.0-beta.32
    vuepress-vite:  2.0.0-beta.32
    vuepress-webpack: Not Found
```

**Comment by Bukunmikuti** [comment] 2021-12-31 16:46
I have this same issue.
Modifications to `.vuepress/config.js` gets highlighted in the terminal but doesn't reflect in browser except I manually restart server
Browser: Chrome

**Comment by meteorlxy** [comment] 2022-01-07 03:25
Duplicate of #611. #611 pointed out the root cause of the bug, so I'll close this one. Thanks for reporting anyway.

**Closed by meteorlxy** 2022-01-07 03:25 UTC
