### ISSUE TITLE
代码行号错位，另外无法安装代码复制插件vuepress-plugin-code-copy

### ISSUE THREAD

**Issue by litaipingcq** [vuepress/vuepress-next#568] opened 2021-12-16 02:31 UTC
![image](https://user-images.githubusercontent.com/37904197/146296978-a7545e37-bb68-4412-847a-075cb43b89c6.png)
行号错位
无法安装vuepress-plugin-code-copy

**Comment by meteorlxy** [comment] 2021-12-17 05:03
Duplicate of #499.

---

vuepress-plugin-code-copy does not support vuepress 2 yet.

**Closed by meteorlxy** 2021-12-17 05:03 UTC
