### ISSUE TITLE
back-to-top plugin not work

### ISSUE THREAD

**Issue by wwavelet** [vuepress/vuepress-next#586] opened 2021-12-23 16:04 UTC
## Bug report

back-to-top plugin not work

### Description

For vuepress@v2，the back-to-top plugin is integrated, but it doesn't work in my project. The <div class="back-to-top"> div is not display when the page scrolls down. But I notice that the back-to-top.xxx.svg is generated in assets, and when I config { themePlugins: {backToTop: false} }, it doesn't generated. So I suggest it's something wrong in runtime.

I tried @vuepress/plugin-back-to-top (extra installed) in vuepress@v1，it works.

### Steps to reproduce

- Reproduction link / repo:

### Environment info

- Browser: chrome 96
- Output of `vuepress info`: 
- "vuepress": "^2.0.0-beta.29"

```bash
# Paste output of `vuepress info` here
```

**Comment by wwavelet** [comment] 2021-12-23 16:06
The \<div class="back-to-top" \> div is not display when the page scrolls down

**Comment by meteorlxy** [comment] 2021-12-23 16:22
Duplicate of #579

**Closed by meteorlxy** 2021-12-23 16:22 UTC

**Comment by Last-Order-Wsk** [comment] 2022-04-01 13:45
When you slide down, the F12 debugging console can see the error message. In fact, you can find the SVG file, but it can't be displayed.I haven't solved it either

**Comment by Mister-Hope** [comment] 2022-04-01 17:01
Please double check if your adblocks is hidden or blocking this button.
